#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="doctors")]
public partial class DoctorsDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  #endregion
	
	public DoctorsDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["doctorsConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DoctorsDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DoctorsDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DoctorsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DoctorsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getDrSpecialty")]
	public ISingleResult<getDrSpecialtyResult> getDrSpecialty([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(4)")] string dr_id)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dr_id);
		return ((ISingleResult<getDrSpecialtyResult>)(result.ReturnValue));
	}
}

public partial class getDrSpecialtyResult
{
	
	private string _specialty;
	
	public getDrSpecialtyResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specialty", DbType="Char(20) NOT NULL", CanBeNull=false)]
	public string specialty
	{
		get
		{
			return this._specialty;
		}
		set
		{
			if ((this._specialty != value))
			{
				this._specialty = value;
			}
		}
	}
}
#pragma warning restore 1591
