<?xml version="1.0" encoding="utf-8"?><Database Name="doctors" Class="DoctorsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=dying_fame;Initial Catalog=doctors;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="doctorsConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="dbo.getDrSpecialty" Method="getDrSpecialty">
    <Parameter Name="dr_id" Type="System.String" DbType="Char(4)" />
    <ElementType Name="getDrSpecialtyResult">
      <Column Name="specialty" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>